import { FormEvent, useEffect, useState } from 'react';
import { api } from '../lib/api';

const labels:Record<string,string>={CLOCK_IN:'Entrada',BREAK_START:'Início intervalo',BREAK_END:'Retorno',CLOCK_OUT:'Saída'};
export default function Adjustments(){
 const [items,setItems]=useState<any[]>([]); const [punches,setPunches]=useState<any[]>([]); const [targetPunchId,setTargetPunchId]=useState(''); const [time,setTime]=useState(''); const [type,setType]=useState('CLOCK_IN'); const [reason,setReason]=useState(''); const [msg,setMsg]=useState('');
 const load=()=>Promise.all([api<any[]>('/adjustments'),api<any[]>('/punches/me')]).then(([a,p])=>{setItems(a);setPunches(p.filter(x=>!x.superseded));}); useEffect(()=>{load().catch(()=>{});},[]);
 function chooseTarget(id:string){setTargetPunchId(id);const p=punches.find(x=>x.id===id);if(p){const d=new Date(p.occurredAt);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);setTime(local);setType(p.type);}}
 async function submit(e:FormEvent){e.preventDefault();setMsg('');try{await api('/adjustments',{method:'POST',body:JSON.stringify({...(targetPunchId?{targetPunchId}:{}),requestedTime:new Date(time).toISOString(),requestedType:type,reason})});setMsg(targetPunchId?'Correção solicitada. O ponto original ficará preservado.':'Inclusão de marcação solicitada.');setReason('');setTime('');setTargetPunchId('');load();}catch(e){setMsg(e instanceof Error?e.message:'Erro');}}
 return <div className="grid-two"><section className="card"><div className="eyebrow">CORREÇÃO AUDITÁVEL</div><h2>Solicitar ajuste</h2><form className="stack" onSubmit={submit}><label>O que deseja corrigir?<select value={targetPunchId} onChange={e=>chooseTarget(e.target.value)}><option value="">Adicionar uma marcação que faltou</option>{punches.slice(0,40).map(p=><option value={p.id} key={p.id}>#{p.recordNumber} · {labels[p.type]??p.type} · {new Date(p.occurredAt).toLocaleString('pt-BR')}</option>)}</select></label><label>Nova data e hora<input type="datetime-local" required value={time} onChange={e=>setTime(e.target.value)}/></label><label>Tipo<select value={type} onChange={e=>setType(e.target.value)}><option value="CLOCK_IN">Entrada</option><option value="BREAK_START">Início intervalo</option><option value="BREAK_END">Retorno</option><option value="CLOCK_OUT">Saída</option></select></label><label>Motivo<textarea required minLength={5} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: esqueci de registrar a saída após atendimento externo."/></label><button className="primary">Enviar solicitação</button>{msg&&<div className="success-box">{msg}</div>}</form></section><section className="card"><div className="eyebrow">HISTÓRICO</div><h2>Solicitações</h2>{items.length===0?<p className="muted">Nenhuma solicitação.</p>:items.map(i=><div className="request-item" key={i.id}><div><b>{labels[i.requestedType]??i.requestedType}</b><span>{new Date(i.requestedTime).toLocaleString('pt-BR')}</span><small>{i.targetPunchId?'Correção de registro existente':'Inclusão de registro'} · {i.reason}</small></div><span className={`status ${i.status.toLowerCase()}`}>{i.status}</span></div>)}</section></div>
}
