import { FormEvent,useEffect,useState } from 'react';
import { api,cacheUser,SessionUser } from '../lib/api';
import BiometricCapture from './BiometricCapture';
import { getBiometricEngineStatus,onBiometricEngineStatus,preloadHuman,type BiometricSample } from '../lib/biometrics';
import { enrollPlatformBiometric,supportsWebAuthn } from '../lib/webauthn';

type State={required:boolean;mustChangePassword:boolean;passwordChanged:boolean;biometricNoticeAcknowledged:boolean;faceEnrolled:boolean;platformBiometricEnrolled:boolean;completed:boolean;completedAt?:string|null};
type Props={user:SessionUser;onComplete:(user:SessionUser)=>void};

const poseLabel:Record<string,string>={FRONT:'frontal',LEFT:'lado esquerdo',RIGHT:'lado direito'};

export default function FirstAccessOnboarding({user,onComplete}:Props){
 const [state,setState]=useState<State|undefined>(user.onboarding as State|undefined);const [security,setSecurity]=useState<any>(null);const [faceEngine,setFaceEngine]=useState(getBiometricEngineStatus());const [currentPassword,setCurrentPassword]=useState('');const [newPassword,setNewPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [msg,setMsg]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [capture,setCapture]=useState<any>(null);
 async function refresh(){const next=await api<State>('/auth/onboarding-status');setState(next);const updated={...user,onboarding:next};cacheUser(updated);if(next.completed)onComplete(updated);return next;}
 useEffect(()=>{const off=onBiometricEngineStatus(setFaceEngine);preloadHuman().catch(()=>{});Promise.all([refresh(),api<any>('/security/status').then(setSecurity)]).catch(e=>setError(e.message));return off;},[]);
 async function changePassword(e:FormEvent){e.preventDefault();setError('');setMsg('');if(newPassword!==confirmPassword)return setError('A confirmação da nova senha não confere.');setBusy(true);try{await api('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})});setCurrentPassword('');setNewPassword('');setConfirmPassword('');setMsg('Senha alterada com sucesso.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Falha ao alterar senha');}finally{setBusy(false);}}
 async function acknowledge(){setBusy(true);setError('');try{await api('/security/biometric-notice/acknowledge',{method:'POST',body:'{}'});setMsg('Ciência biométrica registrada.');await refresh();await api<any>('/security/status').then(setSecurity);}catch(e){setError(e instanceof Error?e.message:'Falha ao registrar ciência');}finally{setBusy(false);}}
 async function startFace(){setBusy(true);setError('');try{await preloadHuman();const c=await api<any>('/security/face-enrollment/challenge');setCapture(c);}catch(e){setError(e instanceof Error?e.message:'Falha ao preparar o reconhecimento facial');}finally{setBusy(false);}}
 async function saveFace(sample:BiometricSample){const c=capture;setCapture(null);setBusy(true);setError('');try{await api('/security/face-enrollment',{method:'POST',body:JSON.stringify({enrollmentToken:c.enrollmentToken,pose:c.nextPose,...sample})});setMsg(`Leitura facial ${poseLabel[c.nextPose]??c.nextPose} cadastrada.`);const next=await refresh();await api<any>('/security/status').then(setSecurity);if(!next.faceEnrolled)setTimeout(()=>startFace().catch(()=>{}),250);}catch(e){setError(e instanceof Error?e.message:'Falha no cadastro facial');}finally{setBusy(false);}}
 async function enrollDigital(){setBusy(true);setError('');try{await enrollPlatformBiometric('Biometria do primeiro acesso');setMsg('Biometria/passkey do dispositivo cadastrada.');await refresh();await api<any>('/security/status').then(setSecurity);}catch(e){setError(e instanceof Error?e.message:'Falha ao cadastrar biometria do dispositivo');}finally{setBusy(false);}}
 const step=state?.mustChangePassword?1:!state?.biometricNoticeAcknowledged?2:!state?.faceEnrolled?3:!state?.platformBiometricEnrolled?4:5;
 return <main className="onboarding-shell"><section className="onboarding-card"><div className="logo-mark">PP</div><div className="eyebrow">PRIMEIRO ACESSO OBRIGATÓRIO</div><h1>Proteja sua conta, {user.name}</h1><p className="muted">Antes de acessar o PontoProof, cada usuário configura a própria senha e identidade biométrica. O ADM/RH não cadastra seu rosto por você.</p>
  <div className="onboarding-progress">{[['1','Senha',state?.passwordChanged],['2','Ciência',state?.biometricNoticeAcknowledged],['3','Face',state?.faceEnrolled],['4','Digital',state?.platformBiometricEnrolled]].map(([n,label,ok]:any)=><div className={ok?'done':step===Number(n)?'current':''} key={n}><b>{ok?'✓':n}</b><span>{label}</span></div>)}</div>
  {step===1&&<form className="onboarding-step" onSubmit={changePassword}><h2>1. Troque a senha temporária</h2><p className="muted">A nova senha deve ter pelo menos 10 caracteres e ser diferente da senha recebida.</p><label>Senha temporária<input type="password" required minLength={6} value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>Nova senha<input type="password" required minLength={10} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label>Confirmar nova senha<input type="password" required minLength={10} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label><button className="primary" disabled={busy}>Salvar nova senha</button></form>}
  {step===2&&<div className="onboarding-step"><h2>2. Ciência do uso biométrico</h2><div className="notice-copy">{security?.biometricNotice?.text??'Carregando aviso biométrico…'}</div><button className="primary" disabled={busy} onClick={acknowledge}>Li e reconheço este aviso</button></div>}
  {step===3&&<div className="onboarding-step"><h2>3. Cadastre sua leitura facial</h2><p className="muted">A câmera fará prova de vida e antispoof. O motor facial começa a carregar em segundo plano assim que você entra no primeiro acesso para reduzir a espera ao abrir a câmera.</p><div className="fact-row"><span>Status facial</span><b>{security?.employee?.faceEnrollmentStatus??'NÃO CADASTRADO'}</b></div><div className="fact-row"><span>Motor facial</span><b>{faceEngine==='ready'?'PRONTO':faceEngine==='loading'?'CARREGANDO':faceEngine==='warming'?'OTIMIZANDO':faceEngine==='error'?'TENTAR NOVAMENTE':'PREPARANDO'}</b></div><button className="primary" disabled={busy||faceEngine==='loading'||faceEngine==='warming'} onClick={startFace}>{faceEngine==='ready'?'Abrir câmera para leitura facial':faceEngine==='error'?'Tentar preparar reconhecimento novamente':'Preparando reconhecimento…'}</button></div>}
  {step===4&&<div className="onboarding-step"><h2>4. Cadastre a biometria do dispositivo</h2><p className="muted">No Windows pode usar Windows Hello/impressão digital; em dispositivos Apple, Touch ID/Face ID; ou outro autenticador/passkey compatível. O PontoProof não recebe a impressão digital bruta.</p><div className="fact-row"><span>WebAuthn neste navegador</span><b>{supportsWebAuthn()?'DISPONÍVEL':'INDISPONÍVEL'}</b></div><button className="primary" disabled={busy||!supportsWebAuthn()} onClick={enrollDigital}>Cadastrar leitura digital / biometria</button>{!supportsWebAuthn()&&<div className="error-box">Use um navegador/dispositivo com WebAuthn e biometria de plataforma habilitada para concluir o primeiro acesso.</div>}</div>}
  {step===5&&<div className="onboarding-step"><h2>Cadastro concluído ✓</h2><p className="muted">Sua senha, leitura facial e autenticação biométrica estão configuradas.</p><button className="primary" onClick={()=>refresh()}>Entrar no PontoProof</button></div>}
  {msg&&<div className="success-box">{msg}</div>}{error&&<div className="error-box">{error}</div>}<button className="ghost onboarding-logout" onClick={()=>{localStorage.removeItem('pontoproof_token');localStorage.removeItem('pontoproof_user');location.reload();}}>Sair e continuar depois</button>
 </section>{capture&&<BiometricCapture title={`Leitura facial — ${poseLabel[capture.nextPose]??capture.nextPose}`} challengeAction={capture.challengeAction} minQuality={Number(security?.policy?.minFaceQualityScore??0.55)} minLiveness={Number(security?.policy?.minLivenessScore??0.65)} minAntiSpoof={Number(security?.policy?.minAntiSpoofScore??0.65)} onCapture={saveFace} onCancel={()=>setCapture(null)}/>}</main>;
}
