import { FormEvent,useEffect,useRef,useState } from 'react';
import { api,cacheUser,SessionUser } from '../lib/api';
import QuickFaceEnrollmentCapture,{type QuickEnrollmentPhoto} from './QuickFaceEnrollmentCapture';
import { enrollPlatformBiometric,supportsWebAuthn } from '../lib/webauthn';

type State={required:boolean;mustChangePassword:boolean;passwordChanged:boolean;biometricNoticeAcknowledged:boolean;faceEnrolled:boolean;faceEnrollmentStatus?:string|null;faceEnrollmentSubmissionStatus?:string|null;faceEnrollmentSubmissionId?:string|null;platformBiometricEnrolled:boolean;completed:boolean;completedAt?:string|null};
type Submission={id:string;status:'PENDING'|'PROCESSING'|'APPROVED'|'NEEDS_RETAKE'|'FAILED';progress:number;reasons?:any;submittedAt:string;processedAt?:string|null};
type Props={user:SessionUser;onComplete:(user:SessionUser)=>void};

function reasonMessages(reasons:any):string[]{
  if(Array.isArray(reasons))return reasons.map(r=>String(r?.message??r?.code??'Imagem precisa ser refeita'));
  if(reasons?.message)return [String(reasons.message)];
  return [];
}

function isLegacyPhotoRecovery(reasons:any){
  return Array.isArray(reasons)&&reasons.some(r=>r?.code==='LEGACY_TMP_RECAPTURE'||r?.code==='EVIDENCE_EXPIRED');
}

export default function FirstAccessOnboarding({user,onComplete}:Props){
 const [state,setState]=useState<State|undefined>(user.onboarding as State|undefined);const [security,setSecurity]=useState<any>(null);const [currentPassword,setCurrentPassword]=useState('');const [newPassword,setNewPassword]=useState('');const [confirmPassword,setConfirmPassword]=useState('');const [msg,setMsg]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [captureOpen,setCaptureOpen]=useState(false);const [submission,setSubmission]=useState<Submission|null>(null);const [popup,setPopup]=useState<{kind:'approved'|'retake'|'failed';title:string;messages:string[]}|null>(null);const lastStatus=useRef<string|null>(null);
 async function refresh(autoComplete=true){const next=await api<State>('/auth/onboarding-status');setState(next);const updated={...user,onboarding:next};cacheUser(updated);if(next.completed&&autoComplete)onComplete(updated);return next;}
 async function loadSubmission(notify=false){const res=await api<{submission:Submission|null}>('/security/face-enrollment/submission/latest');const next=res.submission;setSubmission(next);if(next&&next.status!==lastStatus.current){if(notify){if(next.status==='APPROVED')setPopup({kind:'approved',title:'Imagens aprovadas ✓',messages:['Seu reconhecimento facial foi validado e ativado.']});if(next.status==='NEEDS_RETAKE')setPopup({kind:'retake',title:isLegacyPhotoRecovery(next.reasons)?'Atualização concluída — refaça somente as fotos':'Precisamos refazer algumas imagens',messages:reasonMessages(next.reasons)});if(next.status==='FAILED')setPopup({kind:'failed',title:'A análise encontrou um erro técnico',messages:reasonMessages(next.reasons)});}lastStatus.current=next.status;}return next;}
 useEffect(()=>{Promise.all([refresh(false),api<any>('/security/status').then(x=>{setSecurity(x);if(x.faceEnrollmentSubmission){setSubmission(x.faceEnrollmentSubmission);lastStatus.current=x.faceEnrollmentSubmission.status;if(x.faceEnrollmentSubmission.status==='NEEDS_RETAKE'&&isLegacyPhotoRecovery(x.faceEnrollmentSubmission.reasons))setPopup({kind:'retake',title:'Atualização concluída — refaça somente as fotos',messages:reasonMessages(x.faceEnrollmentSubmission.reasons)});}})]).catch(e=>setError(e.message));},[]);
 useEffect(()=>{const status=submission?.status??state?.faceEnrollmentSubmissionStatus;if(status!=='PENDING'&&status!=='PROCESSING')return;const timer=setInterval(async()=>{try{const next=await loadSubmission(true);if(next?.status==='APPROVED'){await refresh(false);await api<any>('/security/status').then(setSecurity);}}catch{}},2200);return()=>clearInterval(timer);},[submission?.id,submission?.status,state?.faceEnrollmentSubmissionStatus]);
 async function changePassword(e:FormEvent){e.preventDefault();setError('');setMsg('');if(newPassword!==confirmPassword)return setError('A confirmação da nova senha não confere.');setBusy(true);try{await api('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})});setCurrentPassword('');setNewPassword('');setConfirmPassword('');setMsg('Senha alterada com sucesso.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Falha ao alterar senha');}finally{setBusy(false);}}
 async function acknowledge(){setBusy(true);setError('');try{await api('/security/biometric-notice/acknowledge',{method:'POST',body:'{}'});setMsg('Ciência biométrica registrada.');await refresh();await api<any>('/security/status').then(setSecurity);}catch(e){setError(e instanceof Error?e.message:'Falha ao registrar ciência');}finally{setBusy(false);}}
 async function submitFacePhotos(photos:QuickEnrollmentPhoto[]){setError('');const res=await api<{submission:Submission;message:string}>('/security/face-enrollment/submit',{method:'POST',body:JSON.stringify({photos})});setSubmission(res.submission);lastStatus.current=res.submission.status;setCaptureOpen(false);setMsg('Fotos recebidas. A análise facial está acontecendo em segundo plano. Você já pode continuar.');await refresh(false);await api<any>('/security/status').then(setSecurity);}
 async function retryProcessing(){if(!submission)return;setBusy(true);setError('');try{const res=await api<{submission:Submission}>(`/security/face-enrollment/submission/${submission.id}/retry`,{method:'POST',body:'{}'});setSubmission(res.submission);lastStatus.current=res.submission.status;if(res.submission.status==='NEEDS_RETAKE'){setPopup({kind:'retake',title:'Refaça somente as fotos faciais',messages:reasonMessages(res.submission.reasons)});setMsg('Sua senha, ciência biométrica e digital/passkey foram preservadas.');await refresh(false);}else{setPopup(null);setMsg('Análise reenviada sem precisar tirar novas fotos.');}}catch(e){setError(e instanceof Error?e.message:'Falha ao reenviar análise');}finally{setBusy(false);}}
 async function enrollDigital(){setBusy(true);setError('');try{await enrollPlatformBiometric('Biometria do primeiro acesso');setMsg('Biometria/passkey do dispositivo cadastrada.');await refresh(false);await api<any>('/security/status').then(setSecurity);}catch(e){setError(e instanceof Error?e.message:'Falha ao cadastrar biometria do dispositivo');}finally{setBusy(false);}}
 const submissionStatus=submission?.status??state?.faceEnrollmentSubmissionStatus??null;const faceQueued=submissionStatus==='PENDING'||submissionStatus==='PROCESSING';const needsRetake=submissionStatus==='NEEDS_RETAKE';const processingFailed=submissionStatus==='FAILED';const legacyPhotoRecovery=needsRetake&&isLegacyPhotoRecovery(submission?.reasons);
 const step=state?.mustChangePassword?1:!state?.biometricNoticeAcknowledged?2:(!state?.faceEnrolled&&!faceQueued&&!processingFailed?3:!state?.platformBiometricEnrolled?4:!state?.faceEnrolled?5:6);
 return <main className="onboarding-shell"><section className="onboarding-card"><div className="logo-mark">PP</div><div className="eyebrow">PRIMEIRO ACESSO OBRIGATÓRIO</div><h1>Proteja sua conta, {user.name}</h1><p className="muted">Sua foto é capturada em segundos. O processamento facial acontece no servidor sem deixar a câmera travada carregando IA.</p>
  <div className="onboarding-progress">{[['1','Senha',state?.passwordChanged],['2','Ciência',state?.biometricNoticeAcknowledged],['3','Face',state?.faceEnrolled],['4','Digital',state?.platformBiometricEnrolled]].map(([n,label,ok]:any)=><div className={ok?'done':step===Number(n)?'current':''} key={n}><b>{ok?'✓':n}</b><span>{label}{label==='Face'&&faceQueued?' • analisando':''}</span></div>)}</div>
  {step===1&&<form className="onboarding-step" onSubmit={changePassword}><h2>1. Troque a senha temporária</h2><p className="muted">A nova senha deve ter pelo menos 10 caracteres e ser diferente da senha recebida.</p><label>Senha temporária<input type="password" required minLength={6} value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)}/></label><label>Nova senha<input type="password" required minLength={10} value={newPassword} onChange={e=>setNewPassword(e.target.value)}/></label><label>Confirmar nova senha<input type="password" required minLength={10} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)}/></label><button className="primary" disabled={busy}>Salvar nova senha</button></form>}
  {step===2&&<div className="onboarding-step"><h2>2. Ciência do uso biométrico</h2><div className="notice-copy">{security?.biometricNotice?.text??'Carregando aviso biométrico…'}</div><button className="primary" disabled={busy} onClick={acknowledge}>Li e reconheço este aviso</button></div>}
  {step===3&&<div className="onboarding-step"><h2>3. Capture suas fotos faciais</h2><p className="muted">Serão apenas três fotos: frontal, esquerda e direita. Nenhum modelo de reconhecimento precisa carregar antes da câmera abrir.</p><div className="fact-row"><span>Status facial</span><b>{needsRetake?'PRECISA REFAZER':security?.employee?.faceEnrollmentStatus??'NÃO CADASTRADO'}</b></div>{needsRetake&&<div className="warning-box">{legacyPhotoRecovery?'As fotos da versão anterior estavam em armazenamento temporário e expiraram. Somente esta etapa será refeita; sua senha, ciência biométrica e digital/passkey permanecem válidas.':'As fotos anteriores não atingiram os critérios de segurança. Abra a câmera e refaça o conjunto.'}</div>}<button className="primary" disabled={busy} onClick={()=>setCaptureOpen(true)}>{needsRetake?'Refazer fotos agora':'Capturar 3 fotos agora'}</button></div>}
  {step===4&&<div className="onboarding-step"><h2>4. Cadastre a biometria do dispositivo</h2>{faceQueued&&<div className="async-processing-card"><div className="spinner-small"/><div><b>Analisando suas fotos em segundo plano</b><span>Progresso: {submission?.progress??15}% — você não precisa esperar para cadastrar a leitura digital.</span></div></div>}<p className="muted">No Windows pode usar Windows Hello/impressão digital; em dispositivos Apple, Touch ID/Face ID; ou outro autenticador/passkey compatível.</p><div className="fact-row"><span>WebAuthn neste navegador</span><b>{supportsWebAuthn()?'DISPONÍVEL':'INDISPONÍVEL'}</b></div><button className="primary" disabled={busy||!supportsWebAuthn()} onClick={enrollDigital}>Cadastrar leitura digital / biometria</button>{!supportsWebAuthn()&&<div className="error-box">Use um navegador/dispositivo com WebAuthn e biometria de plataforma habilitada.</div>}</div>}
  {step===5&&<div className="onboarding-step"><h2>{processingFailed?'Não foi possível concluir a análise':'Finalizando seu cadastro facial…'}</h2>{processingFailed?<><p className="muted">Suas fotos continuam armazenadas para uma nova tentativa. Você não precisa tirá-las outra vez por causa de um erro técnico.</p><button className="primary" disabled={busy} onClick={retryProcessing}>Tentar processar novamente</button></>:<><div className="async-processing-card"><div className="spinner-small"/><div><b>Servidor analisando as imagens</b><span>{submission?.status==='PROCESSING'?'Reconhecimento facial em andamento':'Aguardando processamento'} • {submission?.progress??15}%</span></div></div><p className="muted">Assim que terminar, você receberá uma confirmação. Se alguma foto precisar ser refeita, o motivo aparecerá em um pop-up.</p></>}</div>}
  {step===6&&<div className="onboarding-step"><h2>Cadastro concluído ✓</h2><p className="muted">Sua senha, leitura facial e autenticação biométrica estão configuradas.</p><button className="primary" onClick={()=>refresh()}>Entrar no PontoProof</button></div>}
  {msg&&<div className="success-box">{msg}</div>}{error&&<div className="error-box">{error}</div>}<button className="ghost onboarding-logout" onClick={()=>{localStorage.removeItem('pontoproof_token');localStorage.removeItem('pontoproof_user');location.reload();}}>Sair e continuar depois</button>
 </section>{captureOpen&&<QuickFaceEnrollmentCapture onSubmit={submitFacePhotos} onCancel={()=>setCaptureOpen(false)}/>} {popup&&<div className="status-popup-backdrop"><div className={`status-popup ${popup.kind}`}><div className="status-popup-icon">{popup.kind==='approved'?'✓':popup.kind==='retake'?'!':'×'}</div><h2>{popup.title}</h2>{popup.messages.length>0&&<ul>{popup.messages.map((m,i)=><li key={i}>{m}</li>)}</ul>}<div className="inline-actions">{popup.kind==='retake'&&<button className="primary" onClick={()=>{setPopup(null);setCaptureOpen(true)}}>Refazer fotos</button>}{popup.kind==='failed'&&<button className="primary" onClick={retryProcessing}>Tentar novamente</button>}{popup.kind==='approved'&&<button className="primary success-button" onClick={async()=>{setPopup(null);await refresh(true)}}>Continuar</button>}<button className="ghost" onClick={()=>setPopup(null)}>Fechar</button></div></div></div>}
 </main>;
}
