const DB='pontoproof-secure-offline';const QUEUE='queue';const META='meta';
export type QueuedPunch={id:string;payload:Record<string,unknown>;queuedAt:string};
function db(){return new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>{const d=req.result;if(!d.objectStoreNames.contains(QUEUE))d.createObjectStore(QUEUE,{keyPath:'id'});if(!d.objectStoreNames.contains(META))d.createObjectStore(META);};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
function req<T>(r:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function key(){const d=await db();const tx=d.transaction(META,'readwrite');const store=tx.objectStore(META);let k=await req(store.get('aes-key')) as CryptoKey|undefined;if(!k){k=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);store.put(k,'aes-key');}return k;}
async function encrypt(value:unknown){const k=await key();const iv=crypto.getRandomValues(new Uint8Array(12));const plain=new TextEncoder().encode(JSON.stringify(value));const cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},k,plain));return {iv:Array.from(iv),cipher:Array.from(cipher)};}
async function decrypt(x:any){const k=await key();const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(x.iv)},k,new Uint8Array(x.cipher));return JSON.parse(new TextDecoder().decode(plain));}
export async function enqueuePunch(payload:Record<string,unknown>){const d=await db();const item={id:crypto.randomUUID(),queuedAt:new Date().toISOString(),sealed:await encrypt(payload)};d.transaction(QUEUE,'readwrite').objectStore(QUEUE).put(item);return {id:item.id,payload,queuedAt:item.queuedAt};}
export async function getQueue():Promise<QueuedPunch[]>{const d=await db();const rows:any[]=await req(d.transaction(QUEUE,'readonly').objectStore(QUEUE).getAll());const out:QueuedPunch[]=[];for(const row of rows){try{out.push({id:row.id,queuedAt:row.queuedAt,payload:await decrypt(row.sealed)});}catch{}}return out.sort((a,b)=>a.queuedAt.localeCompare(b.queuedAt));}
export async function removeQueued(id:string){const d=await db();d.transaction(QUEUE,'readwrite').objectStore(QUEUE).delete(id);}
export async function queueCount(){const d=await db();return req(d.transaction(QUEUE,'readonly').objectStore(QUEUE).count());}
