import { FormEvent, useEffect, useState } from 'react';
import { api } from '../../lib/api';
import { fmtMinutes, monthRange } from '../../lib/format';

type Props={editable:boolean};
export default function Bank({editable}:Props){
 const [items,setItems]=useState<any[]>([]);const [msg,setMsg]=useState('');const [loading,setLoading]=useState(false);const [employeeId,setEmployeeId]=useState('');const [minutes,setMinutes]=useState('');const [reason,setReason]=useState('');const range=monthRange();
 const load=()=>api<any[]>('/bank/overview').then(x=>{setItems(x);if(!employeeId&&x[0])setEmployeeId(x[0].id)});useEffect(()=>{load().catch(()=>{});},[]);
 async function recalc(){setLoading(true);setMsg('');try{await api('/time/recalculate',{method:'POST',body:JSON.stringify({from:range.from,to:range.to})});setMsg('Jornadas do mês recalculadas.');await load();}catch(e){setMsg(e instanceof Error?e.message:'Erro');}finally{setLoading(false)}}
 async function adjust(e:FormEvent){e.preventDefault();setMsg('');try{await api('/bank/adjustments',{method:'POST',body:JSON.stringify({employeeId,minutes:Number(minutes),reason})});setMinutes('');setReason('');setMsg('Ajuste manual lançado e auditado.');await load();}catch(e){setMsg(e instanceof Error?e.message:'Erro');}}
 return <div className={editable?'grid-two':''}>{editable&&<section className="card"><div className="eyebrow">AJUSTE MANUAL</div><h2>Crédito ou débito</h2><form className="stack" onSubmit={adjust}><label>Colaborador<select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}>{items.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></label><label>Minutos <small className="muted">positivo = crédito; negativo = débito</small><input required type="number" value={minutes} onChange={e=>setMinutes(e.target.value)} placeholder="Ex.: 120 ou -60"/></label><label>Motivo<textarea required minLength={5} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ex.: saldo inicial migrado do sistema anterior."/></label><button className="primary">Lançar ajuste</button></form></section>}<section className="card"><div className="card-head"><div><div className="eyebrow">BANCO DE HORAS</div><h2>Saldos acumulados</h2></div><button onClick={recalc} disabled={loading}>{loading?'Calculando...':'Recalcular mês'}</button></div>{msg&&<div className="success-box">{msg}</div>}<div className="table-wrap"><table><thead><tr><th>Colaborador</th><th>Saldo</th><th>Ajustes manuais</th><th>Extra 50%</th><th>Extra 100%</th><th>Déficit</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><b>{i.name}</b><small>{i.employeeNumber}</small></td><td className={i.balanceMinutes<0?'negative':'positive'}>{fmtMinutes(i.balanceMinutes)}</td><td>{fmtMinutes(i.manualMinutes??0)}</td><td>{fmtMinutes(i.overtime50Minutes)}</td><td>{fmtMinutes(i.overtime100Minutes)}</td><td>{fmtMinutes(i.missingMinutes)}</td></tr>)}</tbody></table></div></section></div>;
}
