import { FormEvent,useEffect,useState } from 'react';
import { api } from '../../lib/api';
import { fmtMoney } from '../../lib/format';

type Props={editable:boolean};
const emptyForm={name:'',employeeNumber:'',email:'',password:'',role:'EMPLOYEE',jobTitle:'',salary:'2800',shiftId:'',departmentId:'',worksiteId:'',supervisorId:''};
export default function Employees({editable}:Props){
 const [items,setItems]=useState<any[]>([]),[shifts,setShifts]=useState<any[]>([]),[departments,setDepartments]=useState<any[]>([]),[worksites,setWorksites]=useState<any[]>([]),[security,setSecurity]=useState<any>(null);
 const [msg,setMsg]=useState(''),[editingId,setEditingId]=useState(''),[form,setForm]=useState({...emptyForm});
 const load=()=>Promise.all([api<any[]>('/admin/employees'),api<any[]>('/admin/shifts'),api<any[]>('/admin/departments'),api<any[]>('/admin/worksites'),api<any>('/admin/security-settings')]).then(([e,s,d,w,sec])=>{setItems(e);setShifts(s);setDepartments(d);setWorksites(w);setSecurity(sec);});useEffect(()=>{load().catch(()=>{});},[]);
 function edit(item:any){setEditingId(item.id);setForm({name:item.name??'',employeeNumber:item.employeeNumber??'',email:item.user?.email??'',password:'',role:item.user?.role??'EMPLOYEE',jobTitle:item.jobTitle??'',salary:String((item.salaryCents??0)/100),shiftId:item.shiftId??'',departmentId:item.departmentId??'',worksiteId:item.worksiteId??'',supervisorId:item.supervisorId??''});setMsg('');window.scrollTo({top:0,behavior:'smooth'});}
 function cancel(){setEditingId('');setForm({...emptyForm});setMsg('');}
 async function submit(e:FormEvent){e.preventDefault();setMsg('');try{
   if(editingId){await api(`/admin/employees/${editingId}`,{method:'PATCH',body:JSON.stringify({name:form.name,employeeNumber:form.employeeNumber,role:form.role,jobTitle:form.jobTitle||null,salaryCents:Math.round(Number(form.salary)*100),shiftId:form.shiftId||null,departmentId:form.departmentId||null,worksiteId:form.worksiteId||null,supervisorId:form.supervisorId||null})});setMsg('Cadastro atualizado e auditado.');}
   else {await api('/admin/employees',{method:'POST',body:JSON.stringify({...form,salaryCents:Math.round(Number(form.salary)*100),shiftId:form.shiftId||null,departmentId:form.departmentId||null,worksiteId:form.worksiteId||null,supervisorId:form.supervisorId||null,password:form.password})});setMsg('Usuário criado. No primeiro login ele deverá trocar a senha e cadastrar a própria biometria facial e digital.');}
   setEditingId('');setForm({...emptyForm});await load();
 }catch(e){setMsg(e instanceof Error?e.message:'Erro');}}
 async function toggle(item:any){await api(`/admin/employees/${item.id}`,{method:'PATCH',body:JSON.stringify({active:!item.active})});await load();}
 async function unlock(item:any){await api(`/admin/employees/${item.id}/biometric-unlock`,{method:'POST',body:'{}'});setMsg(`Biometria de ${item.name} desbloqueada.`);await load();}
 return <div className="management-grid">{editable&&<section className="card"><div className="eyebrow">{editingId?'EDIÇÃO':'CADASTRO SEGURO'}</div><h2>{editingId?'Editar colaborador':'Novo colaborador'}</h2><form className="form-grid" onSubmit={submit}>
  <label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Matrícula<input required value={form.employeeNumber} onChange={e=>setForm({...form,employeeNumber:e.target.value})}/></label><label>E-mail<input type="email" required disabled={Boolean(editingId)} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>{!editingId&&<label>Senha temporária<input type="password" required minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>}
  <label>Perfil<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="EMPLOYEE">Colaborador</option><option value="SUPERVISOR">Supervisor</option><option value="HR">RH</option><option value="ADMIN">Administrador</option><option value="AUDITOR">Auditor</option></select></label><label>Cargo<input value={form.jobTitle} onChange={e=>setForm({...form,jobTitle:e.target.value})}/></label><label>Salário base<input type="number" step="0.01" min="0" value={form.salary} onChange={e=>setForm({...form,salary:e.target.value})}/></label>
  <label>Escala<select value={form.shiftId} onChange={e=>setForm({...form,shiftId:e.target.value})}><option value="">Sem escala</option>{shifts.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Setor<select value={form.departmentId} onChange={e=>setForm({...form,departmentId:e.target.value})}><option value="">Sem setor</option>{departments.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Local<select value={form.worksiteId} onChange={e=>setForm({...form,worksiteId:e.target.value})}><option value="">Sem local</option>{worksites.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label>Supervisor<select value={form.supervisorId} onChange={e=>setForm({...form,supervisorId:e.target.value})}><option value="">Sem supervisor</option>{items.filter(x=>x.user?.role==='SUPERVISOR'&&x.id!==editingId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>
  {!editingId&&<div className="form-full biometric-required"><b>Biometria no primeiro acesso</b><p className="muted">O ADM/RH cria apenas a conta e uma senha temporária. O próprio usuário troca a senha e cadastra rosto + biometria/passkey no primeiro login.</p></div>}
  <div className="inline-actions"><button className="primary">{editingId?'Salvar alterações':'Criar colaborador'}</button>{editingId&&<button type="button" className="ghost" onClick={cancel}>Cancelar</button>}</div>{msg&&<div className="success-box form-full">{msg}</div>}
 </form></section>}
 <section className="card span-wide"><div className="eyebrow">EQUIPE</div><h2>Colaboradores</h2><div className="table-wrap"><table><thead><tr><th>Nome</th><th>Matrícula</th><th>Perfil</th><th>Setor</th><th>Escala</th><th>Primeiro acesso</th><th>Face</th><th>Digital</th><th>Proteção</th>{editable&&<th>Salário</th>}<th>Status</th>{editable&&<th/>}</tr></thead><tbody>{items.map(i=><tr key={i.id}><td><b>{i.name}</b><small>{i.user?.email}</small></td><td>{i.employeeNumber}</td><td>{i.user?.role??'—'}</td><td>{i.department?.name??'—'}</td><td>{i.shift?.name??'—'}</td><td><span className={`status ${i.user?.onboardingCompletedAt?'approved':'pending'}`}>{i.user?.onboardingCompletedAt?'CONCLUÍDO':i.user?.mustChangePassword?'SENHA PENDENTE':'BIOMETRIA PENDENTE'}</span></td><td><span className={`status ${i.faceEnrollmentStatus==='ACTIVE'?'approved':'pending'}`}>{i.faceEnrollmentStatus??'NÃO CADASTRADO'}</span></td><td><span className={`status ${(i.user?._count?.webAuthnCredentials??0)>0?'approved':'pending'}`}>{(i.user?._count?.webAuthnCredentials??0)>0?'CADASTRADA':'PENDENTE'}</span></td><td>{i.biometricLockedUntil&&new Date(i.biometricLockedUntil)>new Date()?<span className="status rejected">BLOQUEADA</span>:<span className="status approved">OK</span>}</td>{editable&&<td>{fmtMoney(i.salaryCents??0)}</td>}<td><span className={`status ${i.active?'approved':'rejected'}`}>{i.active?'ATIVO':'INATIVO'}</span></td>{editable&&<td><div className="inline-actions">{i.biometricLockedUntil&&new Date(i.biometricLockedUntil)>new Date()&&<button className="ghost" onClick={()=>unlock(i)}>Desbloquear</button>}<button className="ghost" onClick={async()=>{if(confirm('Revogar o cadastro facial deste usuário? Ele precisará refazer o onboarding facial.')){await api(`/admin/employees/${i.id}/face-reset`,{method:'POST',body:'{}'});setMsg(`Cadastro facial de ${i.name} revogado.`);await load();}}}>Revogar face</button><button className="ghost" onClick={()=>edit(i)}>Editar</button><button className="ghost" onClick={()=>toggle(i)}>{i.active?'Desativar':'Ativar'}</button></div></td>}</tr>)}</tbody></table></div></section>
</div>;
}