import { useEffect,useState } from 'react';
import { api } from '../../lib/api';
export default function SecurityReviews(){
 const [data,setData]=useState<any>({punches:[],attempts:[]}),[note,setNote]=useState<Record<string,string>>({}),[images,setImages]=useState<Record<string,string>>({}),[refs,setRefs]=useState<Record<string,string>>({}),[msg,setMsg]=useState('');
 const load=()=>api<any>('/admin/security-reviews').then(setData);useEffect(()=>{load().catch(()=>{});},[]);
 async function image(kind:'punches'|'attempts',id:string){try{const r=await api<any>(`/security/${kind}/${id}/selfie`);setImages(x=>({...x,[id]:r.dataUrl}));}catch(e){setMsg(e instanceof Error?e.message:'Imagem indisponível');}}
 async function reference(employeeId:string){try{if(refs[employeeId])return;const list=await api<any>(`/admin/employees/${employeeId}/face-references`);const front=list.references?.find((r:any)=>r.pose==='FRONT')??list.references?.[0];if(!front)throw new Error('Referência facial ativa não encontrada');const r=await api<any>(`/security/face-reference/${front.id}/image`);setRefs(x=>({...x,[employeeId]:r.dataUrl}));}catch(e){setMsg(e instanceof Error?e.message:'Referência indisponível');}}
 async function review(id:string,decision:'APPROVED'|'BLOCKED'){try{await api(`/admin/punches/${id}/review`,{method:'POST',body:JSON.stringify({decision,note:note[id]||`Revisão ${decision.toLowerCase()} pelo RH`})});setMsg('Revisão registrada e auditoria atualizada.');await load();}catch(e){setMsg(e instanceof Error?e.message:'Erro');}}
 const photoPair=(id:string,employeeId:string,kind:'punches'|'attempts')=><div className="review-photo-pair"><div><small>Selfie da tentativa</small>{images[id]?<img className="review-selfie" src={images[id]} alt="Selfie protegida da marcação"/>:<button className="ghost" onClick={()=>image(kind,id)}>Ver selfie protegida</button>}</div><div><small>Referência frontal ativa</small>{refs[employeeId]?<img className="review-selfie" src={refs[employeeId]} alt="Referência facial cadastrada"/>:<button className="ghost" onClick={()=>reference(employeeId)}>Ver foto-base</button>}</div></div>;
 return <div className="review-grid"><section className="card"><div className="eyebrow">FILA DE INTEGRIDADE</div><h2>Marcações em revisão</h2>{!data.punches?.length&&<p className="muted">Nenhuma marcação pendente.</p>}{data.punches?.map((p:any)=><div className="review-card" key={p.id}><div className="card-head"><div><b>{p.employee.name}</b><small> #{p.recordNumber} · {p.type} · {new Date(p.occurredAt).toLocaleString('pt-BR')}</small></div><strong>{p.evidence?.proofScore??0}/100</strong></div><div className="metrics"><span>Face: {Math.round((p.evidence?.faceMatchScore??0)*100)}%</span><span>Liveness: {Math.round((p.evidence?.livenessScore??0)*100)}%</span><span>Antispoof: {Math.round((p.evidence?.antiSpoofScore??0)*100)}%</span><span>Geocerca: {String(p.evidence?.geofenceOk??'N/A')}</span></div>{photoPair(p.id,p.employee.id,'punches')}<p className="muted">Pendências: {(p.evidence?.missingRequirementsJson??[]).join(', ')||'sequência/regra operacional'}</p><textarea placeholder="Justificativa da revisão" value={note[p.id]??''} onChange={e=>setNote({...note,[p.id]:e.target.value})}/><div className="inline-actions"><button className="primary" onClick={()=>review(p.id,'APPROVED')}>Aprovar</button><button className="ghost danger" onClick={()=>review(p.id,'BLOCKED')}>Rejeitar marcação</button></div></div>)}</section>
 <section className="card"><div className="eyebrow">TENTATIVAS BLOQUEADAS</div><h2>Possíveis fraudes / falhas</h2>{!data.attempts?.length&&<p className="muted">Nenhuma tentativa bloqueada.</p>}{data.attempts?.map((a:any)=><div className="review-card" key={a.id}><b>{a.employee.name}</b><small> · {a.type} · {new Date(a.attemptedAt).toLocaleString('pt-BR')}</small><p>{a.reason}</p><div className="metrics"><span>Face {Math.round((a.faceMatchScore??0)*100)}%</span><span>Liveness {Math.round((a.livenessScore??0)*100)}%</span><span>Antispoof {Math.round((a.antiSpoofScore??0)*100)}%</span></div>{photoPair(a.id,a.employee.id,'attempts')}<p className="muted">Tentativa bloqueada não vira ponto automaticamente. Se houver justificativa legítima, use o fluxo auditável de ajuste de jornada.</p></div>)}</section>{msg&&<div className="success-box">{msg}</div>}</div>;
}
