import { FormEvent, useEffect, useState } from 'react';
import { api } from '../../lib/api';
const dayOptions=[['MON','Seg'],['TUE','Ter'],['WED','Qua'],['THU','Qui'],['FRI','Sex'],['SAT','Sáb'],['SUN','Dom']];
export default function Shifts(){
 const [items,setItems]=useState<any[]>([]);const [msg,setMsg]=useState('');const [form,setForm]=useState({name:'',startTime:'08:00',endTime:'17:00',breakMinutes:60,dailyMinutes:480,weeklyMinutes:2400,overtimeToleranceMin:10,scheduleDays:['MON','TUE','WED','THU','FRI']});
 const load=()=>api<any[]>('/admin/shifts').then(setItems);useEffect(()=>{load().catch(()=>{});},[]);
 async function submit(e:FormEvent){e.preventDefault();try{await api('/admin/shifts',{method:'POST',body:JSON.stringify({...form,timezone:'America/Maceio'})});setMsg('Escala criada.');setForm({...form,name:''});await load();}catch(e){setMsg(e instanceof Error?e.message:'Erro');}}
 function toggleDay(day:string){setForm({...form,scheduleDays:form.scheduleDays.includes(day)?form.scheduleDays.filter(x=>x!==day):[...form.scheduleDays,day]});}
 return <div className="grid-two"><section className="card"><div className="eyebrow">ESCALAS</div><h2>Criar escala</h2><form className="stack" onSubmit={submit}><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="split"><label>Entrada<input type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></label><label>Saída<input type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></label></div><div className="split"><label>Intervalo (min)<input type="number" value={form.breakMinutes} onChange={e=>setForm({...form,breakMinutes:Number(e.target.value)})}/></label><label>Jornada/dia (min)<input type="number" value={form.dailyMinutes} onChange={e=>setForm({...form,dailyMinutes:Number(e.target.value)})}/></label></div><label>Dias<div className="day-pills">{dayOptions.map(([v,l])=><button type="button" key={v} className={form.scheduleDays.includes(v)?'active':''} onClick={()=>toggleDay(v)}>{l}</button>)}</div></label><button className="primary">Salvar escala</button>{msg&&<div className="success-box">{msg}</div>}</form></section><section className="card"><div className="eyebrow">CADASTRADAS</div><h2>Escalas ativas</h2>{items.map(s=><div className="request-item" key={s.id}><div><b>{s.name}</b><span>{s.startTime}–{s.endTime} · intervalo {s.breakMinutes} min</span><small>{Array.isArray(s.scheduleDays)?s.scheduleDays.join(', '):''} · tolerância {s.overtimeToleranceMin} min</small></div><span className={`status ${s.active?'approved':'rejected'}`}>{s.active?'ATIVA':'INATIVA'}</span></div>)}</section></div>;
}
