import { FormEvent, useEffect, useState } from 'react';
import { api } from '../../lib/api';
const blank={name:'',latitude:'-9.6498',longitude:'-35.7089',radiusM:'150',bluetoothNamePrefix:'',nfcTagId:'',networkGatewayId:''};
export default function Worksites(){
 const [items,setItems]=useState<any[]>([]);const [msg,setMsg]=useState('');const [form,setForm]=useState({...blank});const load=()=>api<any[]>('/admin/worksites').then(setItems);useEffect(()=>{load().catch(()=>{});},[]);
 async function submit(e:FormEvent){e.preventDefault();try{await api('/admin/worksites',{method:'POST',body:JSON.stringify({name:form.name,latitude:Number(form.latitude),longitude:Number(form.longitude),radiusM:Number(form.radiusM),bluetoothNamePrefix:form.bluetoothNamePrefix||undefined,nfcTagId:form.nfcTagId||undefined,networkGatewayId:form.networkGatewayId||undefined})});setForm({...blank});setMsg('Local e provas ambientais cadastrados.');await load();}catch(e){setMsg(e instanceof Error?e.message:'Erro');}}
 async function toggle(w:any){await api(`/admin/worksites/${w.id}`,{method:'PATCH',body:JSON.stringify({active:!w.active})});await load();}
 return <div className="grid-two"><section className="card"><div className="eyebrow">GEOFENCE + PRESENÇA AMBIENTAL</div><h2>Novo local de trabalho</h2><form className="stack" onSubmit={submit}><label>Nome<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="split"><label>Latitude<input required value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})}/></label><label>Longitude<input required value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})}/></label></div><label>Raio permitido (m)<input type="number" min="20" value={form.radiusM} onChange={e=>setForm({...form,radiusM:e.target.value})}/></label><label>Prefixo do Beacon Bluetooth<input placeholder="Ex.: PP-MACEIO-" value={form.bluetoothNamePrefix} onChange={e=>setForm({...form,bluetoothNamePrefix:e.target.value})}/></label><label>ID da tag NFC<input placeholder="Ex.: PONTO-RECEPCAO-01" value={form.nfcTagId} onChange={e=>setForm({...form,nfcTagId:e.target.value})}/></label><label>ID do gateway de rede local<input placeholder="Ex.: GW-MCZ-001" value={form.networkGatewayId} onChange={e=>setForm({...form,networkGatewayId:e.target.value})}/></label><p className="muted">O navegador não fornece SSID Wi-Fi de forma confiável. Quando a política exigir rede, use um gateway local PontoProof que emite uma prova assinada.</p><button className="primary">Cadastrar local</button>{msg&&<div className="success-box">{msg}</div>}</form></section><section className="card"><div className="eyebrow">LOCAIS</div><h2>Geocercas e provas</h2>{items.map(w=><div className="request-item" key={w.id}><div><b>{w.name}</b><span>{w.latitude.toFixed(5)}, {w.longitude.toFixed(5)}</span><small>Raio: {w.radiusM} m · Beacon: {w.bluetoothNamePrefix||'—'} · NFC: {w.nfcTagId||'—'} · Gateway: {w.networkGatewayId||'—'}</small></div><div className="inline-actions"><span className={`status ${w.active?'approved':'rejected'}`}>{w.active?'ATIVO':'INATIVO'}</span><button className="ghost" onClick={()=>toggle(w)}>{w.active?'Desativar':'Ativar'}</button></div></div>)}</section></div>;
}
